<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="assets/images/home-icon.png"/>
        <title>Dashboards</title>
        <!--"assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"->
        <!-- Custom styles for this template-->
        <link href="assets/css/sb-admin.css" rel="stylesheet">
        <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom fonts for this template-->
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <!-- Custom styles for this template-->
        <link href="assets/css/sb-admin.css" rel="stylesheet">
    </head>
</head>
<body style="background-color: white; padding-top: 70px; ">
    <?php
    include_once './assets/templates/header.php';
    //include_once './assets/templates/cards.php';
    //include_once './assets/templates/graficos.php';
    ?>
    <!-- Bootstrap core JavaScript-->
    <script src="assets/vendor/jquery/jquery.min.js"></script>
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="assets/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="assets/js/sb-admin.min.js"></script>
    <!-- Custom scripts for this page-->
    <script src="assets/vendor/chart.js/Chart.min.js"></script>
    <!-- Custom scripts for this page-->
    
</body>
</html>

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="https://upload.wikimedia.org/wikipedia/commons/7/79/Mapa_de_Portugal_-_Distritos_plain.png" usemap="#image-map" style="margin-left: 1200px; zoom:50%">

<map name="image-map" >
    <area target="_top" alt="Faro" title="Faro" href="index.php" coords="300,1116,262,1101,249,1089,235,1100,217,1098,196,1104,168,1088,160,1108,152,1120,151,1140,142,1152,134,1185,141,1190,183,1171,211,1165,237,1170,269,1174,290,1174,309,1187,327,1194,341,1191,367,1177,386,1164,406,1154,424,1151,413,1100,405,1075,380,1076,355,1079,315,1096" shape="poly">
    <area target="" alt="Beja" title="Beja" href="" coords="251,994,221,993,210,1007,207,1015,189,1014,168,1006,170,1030,168,1065,170,1083,196,1097,211,1095,233,1096,254,1088,284,1103,297,1110,307,1101,320,1087,337,1081,365,1072,388,1071,400,1066,406,1051,416,1027,427,1014,442,990,454,965,465,961,481,952,495,952,505,914,464,920,451,898,441,888,407,920,370,911,327,895,301,892,291,893,291,908,268,916,254,931,247,942,258,955,264,965,262,982" shape="poly">
    <area target="" alt="Setubal" title="Setubal" href="" coords="152,850,162,867,170,889,170,928,163,959,153,973,167,987,175,1003,195,1008,203,1009,212,995,234,991,250,987,257,966,248,950,242,931,258,921,276,907,284,897,281,884,260,873,255,856,246,840,222,836,205,830,199,820,213,808,223,802,220,791,205,782,205,769,189,771,179,790,155,785,134,790,121,803,111,809,100,803,81,805,98,837,93,859,94,867,151,838,133,851" shape="poly">
    <area target="" alt="Evora" title="Evora" href="" coords="222,781,241,772,260,765,276,775,285,783,282,767,269,748,271,736,284,729,294,737,300,733,312,747,326,740,343,751,356,750,374,747,385,739,393,734,412,747,417,774,426,775,450,767,454,790,443,809,443,824,437,857,447,873,463,898,470,910,443,882,426,887,408,906,390,911,351,901,309,886,267,870,236,829,222,831,207,822" shape="poly">
    <area target="" alt="Lisboa" title="Lisboa" href="" coords="100,796,117,789,129,746,139,762,153,742,161,726,168,713,152,695,159,688,148,673,135,670,123,660,114,675,97,677,97,665,81,658,75,674,67,694,59,724,52,751,45,772,43,789,52,798,75,799" shape="poly">
    <area target="" alt="Portalegre" title="Portalegre" href="" coords="267,724,253,704,270,690,291,664,326,634,313,618,318,608,336,612,363,589,384,586,397,581,436,626,433,656,449,674,461,686,465,697,482,702,492,715,491,742,480,765,455,782,453,761,420,771,413,737,394,727,375,739,359,743,343,740,314,735,299,724,275,727" shape="poly">
    <area target="" alt="Santarem" title="Santarem" href="" coords="138,658,138,642,157,625,181,619,182,608,193,600,189,584,196,577,191,560,211,554,228,542,234,559,265,552,271,569,274,587,294,590,300,582,304,562,320,579,336,591,338,604,318,600,310,612,312,633,300,645,262,689,251,705,256,730,262,748,271,764,278,769,257,761,238,767,215,778,208,761,186,766,175,783,148,779,157,744,175,714,162,697,171,685,143,666" shape="poly">
    <area target="" alt="Castelo Branco" title="Castelo Branco" href="" coords="266,544,293,520,322,502,340,489,355,481,348,451,366,440,392,430,407,413,434,411,433,433,454,436,464,432,484,441,486,468,493,482,507,497,501,533,493,562,482,576,446,587,410,584,369,581,347,594,321,565,294,558,291,583,275,577" shape="poly">
    <area target="" alt="Leiria" title="Leiria" href="" coords="71,653,98,633,121,596,152,497,174,497,202,500,203,506,218,500,232,504,243,515,263,513,265,491,283,494,286,515,276,535,245,553,228,534,207,543,187,561,189,581,181,606,164,620,139,638,132,659,104,667" shape="poly">
    <area target="" alt="Coimbra" title="Coimbra" href="" coords="157,485,153,454,172,385,198,401,205,394,210,406,224,412,218,431,227,438,251,419,288,424,340,387,347,418,343,455,347,471,331,485,301,509,284,484,264,488,249,511,231,489,204,495,167,491" shape="poly">
    <area target="" alt="Aveiro" title="Aveiro" href="" coords="173,377,180,363,188,372,191,350,182,343,197,272,216,268,234,268,254,263,270,265,284,276,292,276,285,305,260,335,258,350,260,365,255,392,247,415,229,426,222,399,198,387,189,387" shape="poly">
    <area target="" alt="Viseu" title="Viseu" href="" coords="252,410,264,367,274,312,292,303,297,274,279,263,271,256,326,252,377,233,406,226,427,243,421,273,421,281,418,294,411,306,385,298,380,317,381,337,386,361,372,376,321,394,293,413,276,417" shape="poly">
    <area target="" alt="Guarda" title="Guarda" href="" coords="350,437,348,386,385,359,387,331,387,304,418,312,426,272,439,241,462,241,492,267,518,309,516,360,516,395,513,427,495,449,470,423,443,426,443,401,373,433,402,410" shape="poly">
    <area target="" alt="Porto" title="Porto" href="" coords="199,262,175,167,201,179,217,193,245,191,274,186,291,192,315,198,325,224,323,241,311,248,251,260,217,260" shape="poly">
    <area target="" alt="Braga" title="Braga" href="" coords="176,163,176,131,207,122,220,127,230,102,272,98,295,87,293,113,310,132,327,137,338,142,324,172,310,190,263,183,230,187,207,179" shape="poly">
    <area target="" alt="VilaReal" title="VilaReal" href="" coords="333,234,412,214,423,190,438,148,447,72,406,85,375,78,350,70,318,75,298,97,316,125,338,130,326,173,318,194" shape="poly">
    <area target="" alt="Braganca" title="Braganca" href="" coords="419,218,447,140,450,89,453,49,489,52,526,53,558,55,564,106,596,114,619,138,604,179,563,214,530,239,519,260,501,265,476,242,440,234,426,232" shape="poly">
    <area target="" alt="Viana" title="Viana do Castelo" href="" coords="175,126,212,117,228,97,270,90,285,75,278,56,295,31,277,19,253,18,201,28,187,53,164,77,161,98" shape="poly">
</map>